name: Build Flipper Zero Firmware

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          .fbt/cache
        key: ${{ runner.os }}-fbt-cache-${{ hashFiles('Makefile') }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget curl build-essential python3-pip libssl-dev libusb-1.0-0-dev

    - name: Download and setup FBT
      run: |
        curl -s https://raw.githubusercontent.com/flipperdevices/flipperzero-firmware/dev/scripts/fbt.sh | bash

    - name: Build firmware
      run: |
        ./fbt all

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: build/f7/targets/f7-update.fap
